person_follower:
  ros__parameters:
    camera_hfov: 120.0
    image_width: 2304
    image_height: 1296
    yolo_model: "/home/jetson/yolov8n.engine"
    yolo_conf: 0.5
    lidar_range_min: 0.26
    lidar_range_max: 16.0
    smooth_window: 5
    camera_to_lidar_yaw_offset_deg: 0.0
    max_scan_age_sec: 0.2
    min_lidar_angle_margin: 2.0
    max_lidar_angle_margin: 6.0
    target_switch_penalty_deg: 12.0
    lost_count_threshold: 10

camera_publisher:
  ros__parameters:
    width: 2304
    height: 1296
    framerate: 55
    sensor_id: 0

ydlidar_node:
  ros__parameters:
    port: /dev/ydlidar
    frame_id: laser_frame
    baudrate: 230400
    lidar_type: 1
    device_type: 6
    sample_rate: 9
    abnormal_check_count: 4
    fixed_resolution: false
    reversion: true
    inverted: false
    auto_reconnect: true
    isSingleChannel: false
    intensity: false
    support_motor_dtr: false
    angle_min: -180.0
    angle_max: 180.0
    range_min: 0.26
    range_max: 16.0
    frequency: 7.0
    invalid_range_is_inf: false